version: '3.7'

services:
  debezium-connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    hostname: debezium-connect
    container_name: debezium-connect
    healthcheck:
      test: curl --output /dev/null --silent --head --fail localhost:8083
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka1:19092,kafka2:29092,kafka3:39092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect-config"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      LOGGING_LEVEL: "DEBUG"
      CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    volumes:
      - ${DEBEZIUM_TARGET_LOCAL_DIR}:/kafka/connect/debezium-connector-schemaregistry-${KAFKA_VERSION}
    networks:
      - ${GLOBAL_NETWORK}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 90s

  create-debezium-connectors:
    image: itsthenetwork/alpine-curl:latest
    container_name: create-debezium-connectors
    hostname: create-debezium-connectors
    environment:
      KAFKA_CONNECT_CONNECTOR_CONFIG_DIR: "/data/payload/connectors"
      KAFKA_CONNECT_HOSTPORT: "debezium-connect:8083"
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/init-scripts/create-debezium-connectors.sh"]
    volumes:
      - "./scripts/connectors:/data/payload/connectors"
      - "./scripts/utils/create-debezium-connectors.sh:/usr/local/bin/init-scripts/create-debezium-connectors.sh"
    depends_on:
      debezium-connect:
        condition: service_healthy
    networks:
      - ${GLOBAL_NETWORK}

networks:
  food-ordering-system:
    external: true

volumes:
  debezium-connect-schemaregistry-7.5.0:
    driver: local
